# Generated by Django 4.2.2 on 2023-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('user_roll_no', models.CharField(max_length=50, null=True)),
                ('user_marks', models.CharField(max_length=50, null=True)),
                ('user_address', models.TextField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
