# Generated by Django 4.2.2 on 2023-06-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_myuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
    ]
