# Generated by Django 4.2.2 on 2023-06-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_myuser_date_of_birth_remove_myuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='username', max_length=255, null=True),
        ),
    ]
