# Generated by Django 4.2.2 on 2023-06-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_user_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
