# Generated by Django 4.2.2 on 2023-06-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_user_delete_user_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='seller',
        ),
    ]
