# Generated by Django 4.2.2 on 2023-06-30 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_purchase_buyer_purchase_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
