# Generated by Django 4.2.2 on 2023-06-30 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_purchase_seller_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
